version: '3'

services:
  backend:
    build: ./containers/backend
    container_name: disaster-backend
    depends_on:
      - postgres
    ports:
      -  8080:8080
    volumes:
      - ./backend:/application
    command: ['/startApp.sh']
  frontend:
    build: 
      context: ./
      dockerfile: ./containers/frontend/Dockerfile
    container_name: disaster-frontend
    ports:
      -  3000:3000
    volumes:
      - ./frontend:/application
      - /application/node_modules
  postgres:
    image: postgres
    container_name: disaster-postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=victims_db
      - POSTGRES_HOST_AUTH_METHOD=trust
  pgadmin:
    image: dpage/pgadmin4
    container_name: disaster-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"

volumes:
  pgadmin: